/*
  Auto-generated by Spline
*/

import Spline from '@splinetool/react-spline';

function Scene({ ...props }) {
  return (
    <Spline scene="https://prod.spline.design/sEg1NKgOFEcrjWWo/scene.splinecode" />
  )
}

export default Scene